dataset_path: /Users/banzifd/dataset/cifar-100-python

image_path: /home/ubuntu/banzifd/dataset/cifar/cifar-100-python/image/
label_file: /home/ubuntu/banzifd/dataset/cifar/cifar-100-python/label_dict.json

workspace: ~/banzifd/git/ddml/workspace/
dataset_path: ~/banzifd

lr: 0.001
batch: 32
epoch: 5
nb_class: 10

tau: 1.5
beta: 1.0
